clear -all
set_elaborate_single_run_mode off
proc run_decoder_analyze {}  {      analyze -vhdl08 -L GENERIC_TYPES ../../../rtl/generic_components/generic_types.vhd
			    analyze -vhdl08 -L GENERIC_FUNCTIONS ../../../rtl/generic_components/generic_functions.vhd
			    analyze -vhdl08 -L GENERIC_COMPONENTS ../../../rtl/generic_components/generic_components.vhd
			    analyze -vhdl08 -L RS_TYPES ../../rs_common/rs_types.vhd
			    analyze -vhdl08 -L RS_CONSTANTS ../../rs_common/rs_constants.vhd
			    analyze -vhdl08 -L RS_FUNCTIONS ../../rs_common/rs_functions.vhd
			    analyze -vhdl08 -L RS_COMPONENTS ../../rs_common/rs_components.vhd
			    analyze -vhdl08 -L RS_CONSTANTS ../../rs_common/rs_constants.vhd
			    analyze -vhdl08 ../../rs_decoder/rtl/rs_decoder.vhd\
				../../../generic_components/rtl/async_dff.vhd\
				../../../generic_components/rtl/d_sync_flop.vhd\
				../../../generic_components/rtl/no_rst_dff.vhd\
				../../../generic_components/rtl/config_dff_array.vhd\
				../../../generic_components/rtl/sync_dff_array.vhd\
				../../../generic_components/rtl/reg_fifo_array.vhd\
				../../../generic_components/rtl/reg_fifo.vhd\
				../../../generic_components/rtl/flop_cascade.vhd\
				../../rs_common/rs_adder/rs_adder.vhd\
				../../rs_common/rs_multiplier_lut/rs_multiplier_lut.vhd\
				../../rs_common/rs_multiplier/rs_multiplier.vhd\
				../../rs_common/rs_inverse/rs_inverse.vhd\
				../../rs_common/rs_full_multiplier/rs_full_multiplier.vhd\
				../../rs_common/rs_reduce_adder/rs_reduce_adder.vhd\
				../../rs_decoder/rtl/rs_syndrome/rs_syndrome_subunit/rs_syndrome_subunit.vhd\
				../../rs_decoder/rtl/rs_syndrome/rs_syndrome.vhd\
				../../rs_decoder/rtl/rs_berlekamp_massey/rs_berlekamp_massey.vhd\
				../../rs_decoder/rtl/rs_chien_forney/rs_chien/rs_chien.vhd\
				../../rs_decoder/rtl/rs_chien_forney/rs_forney/rs_forney.vhd\
				../../rs_decoder/rtl/rs_chien_forney/rs_chien_forney.vhd 
    #elaborate -vhdl -top rs_decoder -parameter N 15 -parameter K 11 -parameter RS_GF RS_GF_16

}

proc run_analyze {}  {    
    analyze -vhdl08 -L GENERIC_TYPES ../../../generic_components/rtl/generic_types.vhd
    analyze -vhdl08 -L GENERIC_FUNCTIONS ../../../generic_components/rtl/generic_functions.vhd
    analyze -vhdl08 -L GENERIC_COMPONENTS ../../../generic_components/rtl/generic_components.vhd
    analyze -vhdl08 -L RS_TYPES ../../rtl/rs_types.vhd
    analyze -vhdl08 -L RS_CONSTANTS ../../rtl/rs_constants.vhd
    analyze -vhdl08 -L RS_FUNCTIONS ../../rtl/rs_functions.vhd
    analyze -vhdl08 -L RS_COMPONENTS ../../rtl/rs_components.vhd
    analyze -vhdl08 -L RS_CONSTANTS ../../rtl/rs_constants.vhd
    analyze -vhdl08 ../../rtl/rs_decoder.vhd\
                    ../../../generic_components/rtl/async_dff.vhd\
                    ../../../generic_components/rtl/d_sync_flop.vhd\
                    ../../../generic_components/rtl/no_rst_dff.vhd\
                    ../../../generic_components/rtl/config_dff_array.vhd\
                    ../../../generic_components/rtl/sync_dff_array.vhd\
                    ../../../generic_components/rtl/reg_fifo_array.vhd\
                    ../../../generic_components/rtl/reg_fifo.vhd\
                    ../../../generic_components/rtl/up_counter.vhd\
		    ../../../generic_components/rtl/sync_ld_dff.vhd\
		    ../../../generic_components/rtl/flop_cascade.vhd\
                    ../../rtl/rs_adder.vhd\
                    ../../rtl/rs_multiplier_lut.vhd\
                    ../../rtl/rs_multiplier.vhd\
                    ../../rtl/rs_inverse.vhd\
                    ../../rtl/rs_full_multiplier_core.vhd\
                    ../../rtl/rs_full_multiplier.vhd\
                    ../../rtl/rs_reduce_adder.vhd\
                    ../../rtl/rs_syndrome_subunit.vhd\
                    ../../rtl/rs_syndrome.vhd\
                    ../../rtl/rs_berlekamp_massey.vhd\
                    ../../rtl/rs_chien.vhd\
                    ../../rtl/rs_forney.vhd\
                    ../../rtl/rs_chien_forney.vhd 
    analyze -vhdl08 ../../rtl/rs_encoder.vhd\
                    ../../../generic_components/rtl/async_dff.vhd\
                    ../../rtl/rs_remainder_unit.vhd\
                    ../../rtl/rs_syndrome.vhd\
                    ../../rtl/rs_syndrome_subunit.vhd\
                    ../../rtl/rs_encoder_wrapper.vhd
    analyze -vhdl08 rtl/rs_disturber.vhd
    analyze -vhdl08 rtl/rs_codec_with_disturber.vhd
    analyze -vhdl08 rtl/rs_decoder_plus_syndrome.vhd
    analyze -sv09	fv_decoder.sv
#  analyze -vhdl08 -L GENERIC_TYPES ../../../generic_components/generic_types.vhd
#			    analyze -vhdl08 -L GENERIC_COMPONENTS ../../../generic_components/generic_components.vhd
#			    analyze -vhdl08 -L GENERIC_FUNCTIONS ../../../generic_components/generic_functions.vhd
#			    analyze -vhdl08 -L RS_TYPES ../../rs_common/rs_types.vhd
#			    analyze -vhdl08 -L RS_CONSTANTS ../../rs_common/rs_constants.vhd
#			    analyze -vhdl08 -L RS_FUNCTIONS ../../rs_common/rs_functions.vhd
#			    analyze -vhdl08 -L RS_COMPONENTS ../../rs_common/rs_components.vhd
#			    analyze -vhdl08 -L RS_CONSTANTS ../../rs_common/rs_constants.vhd
#			    analyze -vhdl08 ../../rs_decoder/rtl/rs_decoder.vhd\
#				../../../generic_components/async_dff/async_dff.vhd\
#				../../../generic_components/d_sync_flop/d_sync_flop.vhd\
#				../../../generic_components/no_rst_dff/no_rst_dff.vhd\
#				../../../generic_components/config_dff_array/config_dff_array.vhd\
#				../../../generic_components/sync_dff_array/sync_dff_array.vhd\
#				../../../generic_components/fifo_array/reg_fifo_array.vhd\
#				../../../generic_components/fifo/reg_fifo.vhd\
#				../../../generic_components/up_counter/up_counter.vhd\
#				../../rs_common/rs_adder/rs_adder.vhd\
#				../../rs_common/rs_multiplier_lut/rs_multiplier_lut.vhd\
#				../../rs_common/rs_multiplier/rs_multiplier.vhd\
#				../../rs_common/rs_inverse/rs_inverse.vhd\
#				../../rs_common/rs_full_multiplier/rs_full_multiplier.vhd\
#				../../rs_common/rs_reduce_adder/rs_reduce_adder.vhd\
#				../../rs_decoder/rtl/rs_syndrome/rs_syndrome_subunit/rs_syndrome_subunit.vhd\
#				../../rs_decoder/rtl/rs_syndrome/rs_syndrome.vhd\
#				../../rs_decoder/rtl/rs_berlekamp_massey/rs_berlekamp_massey.vhd\
#				../../rs_decoder/rtl/rs_chien_forney/rs_chien/rs_chien.vhd\
#				../../rs_decoder/rtl/rs_chien_forney/rs_forney/rs_forney.vhd\
#				../../rs_decoder/rtl/rs_chien_forney/rs_chien_forney.vhd 
#    analyze -vhdl08 ../../rs_encoder/rtl/rs_encoder.vhd\
#                    ../../../generic_components/async_dff/async_dff.vhd\
#                    ../../rs_common/rs_adder/rs_adder.vhd\
#                    ../../rs_common/rs_multiplier_lut/rs_multiplier_lut.vhd\
#                    ../../rs_common/rs_multiplier/rs_multiplier.vhd\
#                    ../../rs_encoder/rtl/rs_remainder_unit/rs_remainder_unit.vhd\
#		    ../../rs_decoder/rtl/rs_syndrome/rs_syndrome.vhd\
#		    ../../rs_decoder/rtl/rs_syndrome/rs_syndrome_subunit/rs_syndrome_subunit.vhd\
#		    ../../rs_encoder/rtl/rs_encoder_wrapper.vhd
#    analyze -vhdl08 rtl/rs_error_generator.vhd
#    analyze -vhdl08 rtl/rs_codec_wrapper.vhd
}

proc run_design_compilation {N K RS_GF mode} {
    clear -all
    run_analyze
    if {$mode == "only_decoder"} {
        elaborate -vhdl -top rs_decoder -parameter N $N -parameter K $K -parameter RS_GF $RS_GF
        connect -bind -auto fv_decoder mod2 -auto -elaborate 
    } elseif {$mode == "disturber"} {
        elaborate -vhdl -top rs_codec_with_disturber -parameter N $N -parameter K $K -parameter RS_GF $RS_GF
    } elseif {$mode == "syndrome"} {
        elaborate -vhdl -top rs_decoder_plus_syndrome -parameter N $N -parameter K $K -parameter RS_GF $RS_GF
    }
}
