function createfigure(X1, Y1, X2, Y2, X3, Y3, X4, Y4, X5, Y5, Y6, Y7, Y8, Y9, Y10, Y11, Y12, Y13, Y14, Y15, X6, Y16, Y17, Y18, Y19, Y20, Y21, Y22, Y23, Y24, Y25, Y26, Y27, Y28, Y29, Y30)
%CREATEFIGURE(X1, Y1, X2, Y2, X3, Y3, X4, Y4, X5, Y5, Y6, Y7, Y8, Y9, Y10, Y11, Y12, Y13, Y14, Y15, X6, Y16, Y17, Y18, Y19, Y20, Y21, Y22, Y23, Y24, Y25, Y26, Y27, Y28, Y29, Y30)
%  X1:  vector of x data
%  Y1:  vector of y data
%  X2:  vector of x data
%  Y2:  vector of y data
%  X3:  vector of x data
%  Y3:  vector of y data
%  X4:  vector of x data
%  Y4:  vector of y data
%  X5:  vector of x data
%  Y5:  vector of y data
%  Y6:  vector of y data
%  Y7:  vector of y data
%  Y8:  vector of y data
%  Y9:  vector of y data
%  Y10:  vector of y data
%  Y11:  vector of y data
%  Y12:  vector of y data
%  Y13:  vector of y data
%  Y14:  vector of y data
%  Y15:  vector of y data
%  X6:  vector of x data
%  Y16:  vector of y data
%  Y17:  vector of y data
%  Y18:  vector of y data
%  Y19:  vector of y data
%  Y20:  vector of y data
%  Y21:  vector of y data
%  Y22:  vector of y data
%  Y23:  vector of y data
%  Y24:  vector of y data
%  Y25:  vector of y data
%  Y26:  vector of y data
%  Y27:  vector of y data
%  Y28:  vector of y data
%  Y29:  vector of y data
%  Y30:  vector of y data

%  Auto-generated by MATLAB on 15-Jan-2020 21:50:12

% Create figure
figure1 = figure;

% Create subplot
subplot1 = subplot(2,3,1,'Parent',figure1);
hold(subplot1,'on');

% Create plot
plot(X1,Y1,'Parent',subplot1,'Color',[0 0 0]);

% Create plot
plot(X2,Y2,'Parent',subplot1,'LineStyle','--','Color',[0 0 0]);

% Create plot
plot(X3,Y3,'Parent',subplot1,'LineStyle','-.','Color',[0 0 0]);

% Create plot
plot(X4,Y4,'Parent',subplot1,'Marker','*','Color',[0 0 0]);

% Create plot
plot(X5,Y5,'Parent',subplot1,'Marker','square','Color',[0 0 0]);

% Create xlabel
xlabel('T');

% Create ylabel
ylabel('LE');

% Create title
title('RS Encoder: Logic Cell Utilization');

% Create subplot
subplot2 = subplot(2,3,2,'Parent',figure1);
hold(subplot2,'on');

% Create plot
plot(X1,Y6,'Parent',subplot2,'Color',[0 0 0]);

% Create plot
plot(X2,Y7,'Parent',subplot2,'LineStyle','--','Color',[0 0 0]);

% Create plot
plot(X3,Y8,'Parent',subplot2,'LineStyle','-.','Color',[0 0 0]);

% Create plot
plot(X4,Y9,'Parent',subplot2,'Marker','*','Color',[0 0 0]);

% Create plot
plot(X5,Y10,'Parent',subplot2,'Marker','square','Color',[0 0 0]);

% Create xlabel
xlabel('T');

% Create ylabel
ylabel('RE');

% Create title
title('RS Encoder: Register Utilization');

% Create subplot
subplot3 = subplot(2,3,3,'Parent',figure1);
hold(subplot3,'on');

% Create plot
plot(X1,Y11,'Parent',subplot3,'Color',[0 0 0]);

% Create plot
plot(X2,Y12,'Parent',subplot3,'LineStyle','--','Color',[0 0 0]);

% Create plot
plot(X3,Y13,'Parent',subplot3,'LineStyle','-.','Color',[0 0 0]);

% Create plot
plot(X4,Y14,'Parent',subplot3,'Marker','*','Color',[0 0 0]);

% Create plot
plot(X5,Y15,'Parent',subplot3,'Marker','square','Color',[0 0 0]);

% Create xlabel
xlabel('T');

% Create ylabel
ylabel('F_{max} (kHz)');

% Create title
title('RS Encoder: Maximum clock frequency');

% Create subplot
subplot4 = subplot(2,3,4,'Parent',figure1);
hold(subplot4,'on');

% Create plot
plot(X6,Y16,'Parent',subplot4,'Color',[0 0 0]);

% Create plot
plot(X2,Y17,'Parent',subplot4,'LineStyle','--','Color',[0 0 0]);

% Create plot
plot(X3,Y18,'Parent',subplot4,'LineStyle','-.','Color',[0 0 0]);

% Create plot
plot(X4,Y19,'Parent',subplot4,'Marker','*','Color',[0 0 0]);

% Create plot
plot(X5,Y20,'Parent',subplot4,'Marker','square','Color',[0 0 0]);

% Create xlabel
xlabel('T');

% Create ylabel
ylabel('LE');

% Create title
title('RS Decoder: Logic Cell Utilization');

% Create subplot
subplot5 = subplot(2,3,5,'Parent',figure1);
hold(subplot5,'on');

% Create plot
plot(X6,Y21,'Parent',subplot5,'Color',[0 0 0]);

% Create plot
plot(X2,Y22,'Parent',subplot5,'LineStyle','--','Color',[0 0 0]);

% Create plot
plot(X3,Y23,'Parent',subplot5,'LineStyle','-.','Color',[0 0 0]);

% Create plot
plot(X4,Y24,'Parent',subplot5,'Marker','*','Color',[0 0 0]);

% Create plot
plot(X5,Y25,'Parent',subplot5,'Marker','square','Color',[0 0 0]);

% Create xlabel
xlabel('T');

% Create ylabel
ylabel('RE');

% Create title
title('RS Decoder: Register Utilization');

% Create subplot
subplot6 = subplot(2,3,6,'Parent',figure1);
hold(subplot6,'on');

% Create plot
plot(X6,Y26,'Parent',subplot6,'DisplayName','m = 4','Color',[0 0 0]);

% Create plot
plot(X2,Y27,'Parent',subplot6,'DisplayName','m = 5','LineStyle','--',...
    'Color',[0 0 0]);

% Create plot
plot(X3,Y28,'Parent',subplot6,'DisplayName','m = 6','LineStyle','-.',...
    'Color',[0 0 0]);

% Create plot
plot(X4,Y29,'Parent',subplot6,'DisplayName','m = 7','Marker','*',...
    'Color',[0 0 0]);

% Create plot
plot(X5,Y30,'Parent',subplot6,'DisplayName','m = 8','Marker','square',...
    'Color',[0 0 0]);

% Create xlabel
xlabel('T');

% Create ylabel
ylabel('F_{max} (kHz)');

% Create title
title('RS Decoder: Maximum Clock Frequency');

% Create legend
legend1 = legend(subplot6,'show');
set(legend1,...
    'Position',[0.916908915400097 0.110673335234707 0.0632267435146279 0.150684927424339]);

