function createfigure(X1, Y1, X2, Y2, X3, YMatrix1, Y3, Y4, YMatrix2, Y5, Y6, YMatrix3)
%CREATEFIGURE(X1, Y1, X2, Y2, X3, YMATRIX1, Y3, Y4, YMATRIX2, Y5, Y6, YMATRIX3)
%  X1:  vector of x data
%  Y1:  vector of y data
%  X2:  vector of x data
%  Y2:  vector of y data
%  X3:  vector of x data
%  YMATRIX1:  matrix of y data
%  Y3:  vector of y data
%  Y4:  vector of y data
%  YMATRIX2:  matrix of y data
%  Y5:  vector of y data
%  Y6:  vector of y data
%  YMATRIX3:  matrix of y data

%  Auto-generated by MATLAB on 04-Feb-2020 11:31:38

% Create figure
figure1 = figure('PaperType','<custom>','PaperSize',[5 5]);

% Create axes
axes1 = axes('Parent',figure1,...
    'Position',[0.13655844155844 0.744615384615385 0.58 0.22]);
hold(axes1,'on');

% Create plot
plot(X1,Y1,'Parent',axes1,'Color',[0 0 0]);

% Create plot
plot(X2,Y2,'Parent',axes1,'LineStyle','--','Color',[0 0 0]);

% Create multiple lines using matrix input to plot
plot1 = plot(X3,YMatrix1,'Parent',axes1,'Color',[0 0 0]);
set(plot1(1),'LineStyle','-.');
set(plot1(2),'Marker','*');
set(plot1(3),'Marker','square');

% Create ylabel
ylabel('LE');

% Create title
title('Logic Cell Utilization','FontWeight','bold');

%% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[0 16]);
% Set the remaining axes properties
set(axes1,'XTick',[0 2 4 6 8 10 12 14 16]);
% Create axes
axes2 = axes('Parent',figure1,...
    'Position',[0.148181818181817 0.410769230769231 0.58 0.22]);
hold(axes2,'on');

% Create plot
plot(X1,Y3,'Parent',axes2,'Color',[0 0 0]);

% Create plot
plot(X2,Y4,'Parent',axes2,'LineStyle','--','Color',[0 0 0]);

% Create multiple lines using matrix input to plot
plot2 = plot(X3,YMatrix2,'Parent',axes2,'Color',[0 0 0]);
set(plot2(1),'LineStyle','-.');
set(plot2(2),'Marker','*');
set(plot2(3),'Marker','square');

% Create ylabel
ylabel('RE');

% Create title
title('Register Utilization');

%% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes2,[0 16]);
% Set the remaining axes properties
set(axes2,'XTick',[0 2 4 6 8 10 12 14 16]);
% Create axes
axes3 = axes('Parent',figure1,...
    'Position',[0.143636363636362 0.0787996744226436 0.58 0.22]);
hold(axes3,'on');

% Create plot
plot(X1,Y5,'Parent',axes3,'DisplayName','m = 4','Color',[0 0 0]);

% Create plot
plot(X2,Y6,'Parent',axes3,'DisplayName','m = 5','LineStyle','--',...
    'Color',[0 0 0]);

% Create multiple lines using matrix input to plot
plot3 = plot(X3,YMatrix3,'Parent',axes3,'Color',[0 0 0]);
set(plot3(1),'DisplayName','m = 6','LineStyle','-.');
set(plot3(2),'DisplayName','m = 7','Marker','*');
set(plot3(3),'DisplayName','m = 8','Marker','square');

% Create ylabel
ylabel('F_{max} (kHz)');

% Create title
title('Maximum Clock Frequency');

%% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes3,[0 16]);
% Set the remaining axes properties
set(axes3,'XTick',[0 2 4 6 8 10 12 14 16]);
% Create legend
legend1 = legend(axes3,'show');
set(legend1,...
    'Position',[0.752716728116655 0.0819467169425773 0.194444442512812 0.132845123746314],...
    'FontSize',8,...
    'FontName','Arial');

% Create textbox
annotation(figure1,'textbox',...
    [0.413964165464162 0.342034953236289 0.0671296283188794 0.0404530737102997],...
    'String',{'b'},...
    'FontName','Arial',...
    'FontAngle','italic',...
    'EdgeColor','none');

% Create textbox
annotation(figure1,'textbox',...
    [0.409376623376619 0.00936496111237142 0.0648148135730514 0.0404530737102996],...
    'String',{'c'},...
    'FontName','Arial',...
    'FontAngle','italic',...
    'EdgeColor','none');

% Create textbox
annotation(figure1,'textbox',...
    [0.398012987012984 0.679126053262542 0.0671296283188794 0.0404530737102996],...
    'String',{'a'},...
    'FontName','Arial',...
    'FontAngle','italic',...
    'EdgeColor','none');

